<?php
session_start();
?>
<html>
<body>
<?php
error_reporting(0);
if(isset($_POST['editr']))
{
$p=$_POST['password'];
$np=$_POST['npassword'];
$cp=$_POST['cpassword'];
}
$user_name="root";
$password="";
$database="project1";
$server = "127.0.0.1";
$db_handle=mysql_connect($server,$user_name,$password);
$db_found=mysql_select_db($database,$db_handle);
if($db_found)
{
$sql1="select * from admin";
$result1=mysql_query($sql1);
$db1=mysql_fetch_assoc($result1);
if($db1['password']==$p)
{
if($np==$cp)
{
$sql="UPDATE `project1`.`admin` SET `password` = '".$np."'";
$result=mysql_query($sql);
$_SESSION['adminpassword']=$np;
$_SESSION['p']=1;
header("location:admin.php");
}
else
{
$_SESSION['icp']=1;
header("location:admin.php");
}
}
else
{
$_SESSION['ip']=1;
header("location:admin.php");

}
}
?>
</body>
</html>